name: Vérifier index.html

on: [push, pull_request]

jobs:
  check-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Vérifier la présence de <title> dans index.html
      run: |
        if grep -q "<title>" index.html; then
          echo "Le fichier index.html contient une balise <title>."
        else
          echo "Erreur: Le fichier index.html ne contient pas de balise <title>."
          exit 1
        fi